name: Pre-configure Container
description: Run container configuration for containerized builds.
runs:
  using: composite
  steps:
    - name: Get sudo and latest git tools
      run: |
          if [ -f /.dockerenv ]; then
            apt-get update && apt-get install -y sudo && apt-get install -y git
            git config --global --add safe.directory '*'
          else
            echo 'Skipping. Current job is not running inside a container.'
          fi