name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  linux-x86_64-cmake-1:
    name: Linux x86_64 (cmake, docker) one
    runs-on: faiss-amd-MI200
    container: ubuntu:22.04
    steps:
      - name: Container setup
        run: |
            if [ -f /.dockerenv ]; then
              apt-get update && apt-get install -y sudo && apt-get install -y git
              git config --global --add safe.directory '*'
              sudo rm -rf $HOME/*
            else
              echo 'Skipping. Current job is not running inside a container.'
            fi
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test (cmake)
        uses: ./.github/actions/build_cmake
  linux-x86_64-cmake-2:
    name: Linux x86_64 (cmake, docker) two
    runs-on: faiss-amd-MI200
    container: ubuntu:22.04
    steps:
      - name: Container setup
        run: |
            if [ -f /.dockerenv ]; then
              apt-get update && apt-get install -y sudo && apt-get install -y git
              git config --global --add safe.directory '*'
            else
              echo 'Skipping. Current job is not running inside a container.'
            fi
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test (cmake)
        uses: ./.github/actions/build_cmake