name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  linux-x86_64-cmake:
    name: Linux x86_64 (cmake, docker) - 1
    runs-on: faiss-amd-MI200
    container: ubuntu:22.04
    steps:
      - name: Container setup
        uses: ./.github/actions/container_setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test (cmake)
        uses: ./.github/actions/build_cmake
  linux-x86_64-cmake:
    name: Linux x86_64 (cmake, docker) - 2
    runs-on: faiss-amd-MI200
    container: ubuntu:22.04
    steps:
      - name: Container setup
        uses: ./.github/actions/container_setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test (cmake)
        uses: ./.github/actions/build_cmake