name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  windows-x86_64-conda:
    name: Windows x86_64 (conda)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - uses: ./.github/actions/build_conda
