name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
env:
  OMP_NUM_THREADS: '10'
  MKL_THREADING_LAYER: GNU
jobs:
  linux-x86_64-cmake-nocontainer:
    name: Linux x86_64 (cmake, no-container)
    runs-on: faiss-amd-MI200
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
  linux-x86_64-cmake:
    name: Linux x86_64 (cmake, docker)
    runs-on: faiss-amd-MI200
    container: ubuntu:22.04
    steps:
      - name: Container setup
        run: |
            apt-get update && apt-get install -y sudo && apt-get install -y git
            git config --global --add safe.directory '*'
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build_cmake
